name: Build on Linux

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install libcurl development package
      run: sudo apt-get update && sudo apt-get install -y libcurl4-openssl-dev

    - name: Set up CMake
      run: |
        sudo apt-get install -y cmake

    - name: Build project
      run: |
        cd Builds/LinuxMakefile
        CONFIG=Release make
