name: Build, Release, and Artifact on Linux

on:
  push:
    branches:
      - master

jobs:
  build_and_release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install libcurl development package
      run: sudo apt-get update && sudo apt-get install -y libcurl4-openssl-dev

    - name: Set up CMake
      run: |
        sudo apt-get install -y cmake

    - name: Build project
      run: |
        cd Builds/LinuxMakefile
        CONFIG=Release make

    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      with:
        token: ${{ secrets.MY_TOKEN }}  # 使用你的自定义 token
      env:
        MY_TOKEN: ${{ secrets.MY_TOKEN }}
      ...
      
    - name: Upload release asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: Builds/LinuxMakefile/aooserver   # 替换成你的文件路径
        asset_name: aooserver                        # 替换成你的文件名称
        asset_content_type: application/octet-stream # 替换成你的文件类型
      env:
        MY_TOKEN: ${{ secrets.MY_TOKEN }}
      ...
